flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = TextAreaField('Текст', validators=[DataRequired()])
    submit = SubmitField('Сохранить')

flask_blog/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request,
                   abort, Blueprint)
from flask_login import login_required, current_user
from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/allpost')
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,
                                                                  per_page=5)
    return render_template('allpost.html', posts=posts, title='Все записи')


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        print(form.title.data, form.content.data, current_user)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html', title='Новый пост',
                           form=form)


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
def post_edit(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обнавлён!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Редактирование поста',
                           form=form)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост удалён', 'success')
    return redirect(url_for('posts.allpost'))

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from .forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                         RequestResetForm, ResetPasswordForm)
from .utils import save_picture
from flask_blog.users.utils import send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).\
            decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана!'
              'Теперь вы можете войти в систему', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(
                url_for('posts.allpost'))
        else:
            flash('Войти не удалось. Пожалуйста, '
                  'проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).\
            order_by(Post.date_posted.desc()).\
            paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics' +
                                            current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, posts=posts,
                           user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).\
        order_by(Post.date_posted.desc()).\
        paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с '
              'инструкциями по сбросу пароля', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен!'
              'Теперь Вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Сброс пароля', form=form)

flask_blog/templates/account.html
{% extends 'layout.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<form method="post" action="">
    {{ form.hidden_tag() }}
    <h3 class="content-header">Редактирование профиля</h3>
    <div class="form-control">
        {{ form.username.label }}
        {% if form.username.errors %}
            {{ form.username }}
            {% for error in form.username.errors %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.username }}
        {% endif %}
    </div>
    <div class="form-control">
        {{ form.email.label }}
        {% if form.email.errors %}
            {{ form.email }}
            {% for err in form.email.errors %}
                <p><b>{{ err }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.email }}
        {% endif %}
    </div>
    <div class="form-control">
        <img class='img__avatar' src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}" alt="pics">
        {{ form.picture.label }}
        {{ form.picture }}
        {% if form.picture.errors %}
          {% for error in form.picture.errors %}
              <span class="text-danger">{{ error }}</span></br>
          {% endfor %}
      {% endif %}
    </div>
    <div class="form-control">
        {{ form.submit }}
    </div>

</form>
{% endblock content %}

flask_blog/templates/allpost.html
{% extends 'layout.html' %}
{% block title %}
    <title>{{ title }}</title>
{% endblock %}
<body>
{%  block content %}
    <h4 class="min-header">
        Ваши посты: <a href="{{ url_for('users.user_posts', username=current_user.username) }}">{{ current_user.username }}</a>
    </h4>
    <h1>Все посты</h1>
    {% for post in posts.items %}
        <div class="border-div">
            <img class='img__avatar' src="{{ url_for ('static', filename='profile_pics/' + post.author.image_file) }}" alt="pics">
            <h4 class="min-header"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
            <p>{{ post.content }}</p>
        </div>
    {% endfor %}
{% endblock content %}
</body>

flask_blog/templates/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
{% block content %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <h3 class="content-header">Новый пост</h3>
    <div class="form-cotrol">
        {{ form.title.label }}
        {% if form.title.errors %}
            {{ form.title }}
            {% for error in form.title.errors %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.title }}
        {% endif %}
    </div>
    <div class="form-cotrol">
        {{ form.content.label }}
        {% if form.content.errors %}
            {{ form.content }}
            {% for error in form.content.errors %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.content }}
        {% endif %}
    </div>

    <div class="form-cotrol">
        {{ form.submit }}
    </div>
</form>
{% endblock %}
</body>
</html>

flask_blog/templates/home.html
{% extends "layout.html" %}

{% block style %}
<style>
    .top-header {
        font-size: 64px;
        color: #1F3F68;
    }
</style>
{% endblock style %}

{% block content %}
<h3 class="content-header">Lorem ipsum dolor sit.</h3>
<h4 class="min-header">Lorem ipsum dolor sit amet, consectetur.</h4>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda cum debitis modi praesentium suscipit
    voluptate.</p>
<h3 class="content-header">Lorem ipsum dolor sit.</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore nesciunt odio repellendus, similique tempora
    voluptas?</p>
<h3 class="content-header">Lorem ipsum dolor sit amet.</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, maxime!</p>

{% endblock content %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% if title %}
        <title>My Site - {{title}}</title>
    {% else %}
        <title>My Site</title>
    {% endif %}

    {% block head %}    {% endblock head %}

    {% block style %}    {% endblock style %}

</head>
<body>
<div class="top__header">
    <div class="container__main top-box">
        <ul class="header__top">
            <li>Hello,
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('users.account') }}">{{ current_user.username }}</a>
                {% else %}
                    Guest
                {% endif %}
            </li>
            <li><a href="/">Главная</a></li>
        {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('users.logout') }}">Выйти</a></li>
            <li><a href="{{ url_for('posts.allpost') }}">Записи блога</a></li>
        {% else %}
            <li><a href="{{ url_for('users.login') }}">Войти</a></li>
        {% endif %}
        </ul>
            </h4>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {{ message }}
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="top__info">
            <h1 class="top__heading">Блог незивестного автора</h1>
            <p class="text top__text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Asperiores dicta error expedita nam quae ullam?
            </p>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('posts.new_post') }}" class="top__button">Напиши свой пост</a>
        {% else %}
            <a href="{{ url_for('users.register') }}" class="top__button">Регистрация</a>
        {% endif %}
        </div>
    </div>
</div>
<div class="container__main">
    {% block content %}  {% endblock content %}
</div>
<div class="footer">
    <div class="container__main">
        <div class="footer__top">
            <h3>Lorem ipsum dolor sit.</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti est iste officiis.</p>
        </div>
        <hr>
        <div class="footer__bottom">
            <ul class="footer__info">
                <li>Lorem ipsum dolor sit amet.</li>
                <li>+7999999999</li>
                <li>example@inbox.ru</li>
            </ul>
        </div>
    </div>
</div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flask_blog/templates/login.html
{% extends 'layout.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<form method="post" action="">
    {{ form.hidden_tag() }}
    <h3 class="content-header">Вход</h3>
    <div class="form-control">
        {{ form.email.label }}
        {% if form.email.errors %}
            {{ form.email}}
            {% for error in form.email.erorrs %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.email }}
        {% endif %}
    </div>
    <div class="form-control">
        {{ form.password.label }}
        {% if form.password.errors %}
            {{ form.password }}
            {% for error in form.password.erorrs %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.password }}
        {% endif %}
    </div>
    <div class="form-control">
        {{ form.submit }}
        <a href="{{ url_for('users.reset_request') }}">Забыли пароль?</a>
    </div>


</form>
{% endblock content %}

flask_blog/templates/post.html
{% extends 'layout.html' %}
{% block title %}
    <title>{{ title }}</title>
{% endblock %}
<body>
{%  block content %}
<h3 class="content-header">{{ post.title }}</h3>
    <div class="border-div">
        <img class='img__avatar' src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="">
        <p style="text-align: center"><b>Добавлен {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</b></p>
        <p>{{ post.content }}</p>
        {% if post.author == current_user %}
            <div class="card-footer" style="font-size: 20px;"> {% if post.author == current_user %}<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.post_edit', post_id=post.id) }}">Обновить</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Удалить</button>
        {% endif %}
            </div>
    {% endif %}
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Удалить">
              </form>
            </div>
          </div>
        </div>
    </div>
{% endblock content %}
</body>

flask_blog/templates/register.html
{% extends "layout.html" %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <h3 class="content-header">Регистрация</h3>
    <div class="form-control">
        {{ form.username.label }}
        {% if form.username.errors %}
            {{ form.username }}
            {% for error in form.username.errors %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.username }}
        {% endif %}
    </div>
    <div class="form-control">
        {{ form.email.label }}
        {% if form.email.errors %}
            {{ form.email }}
            {% for error in form.email.errors %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.email }}
        {% endif %}
    </div>
    <div class="form-control">
        {{ form.password.label }}
        {% if form.password.errors %}
            {{ form.password }}
            {% for error in form.password.errors %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.password }}
        {% endif %}
    </div>
    <div class="form-control">
        {{ form.confirm_password.label }}
        {% if form.confirm_password.errors %}
            {{ form.confirm_password }}
            {% for error in form.confirm_password.errors %}
                <p><b>{{ error }}</b></p>
            {% endfor %}
        {% else %}
            {{ form.confirm_password }}
        {% endif %}
    </div>
    <div class="form-control">
        {{ form.submit }}
    </div>

</form>
{% endblock content %}

flask_blog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Сброс пароля</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/reset_token.html
{% extends 'layout.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    {{ form.password.label }}
    {% if form.password.errors %}
        {% for error in form.password.errors %}
            <span>{{ error }}</span>
        {% endfor %}
    {% else %}
        {{ form.password }}
    {% endif %}

    {{ form.confirm_password.label }}
    {% if form.confirm_password.errors %}
        {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
        {% endfor %}
    {% else %}
        {{ form.confirm_password }}
    {% endif %}
    {{ form.submit }}
</form>
{% endblock %}

flask_blog/templates/user_posts.html
{% extends 'layout.html' %}
{% block title %}
    <title>{{ title }}</title>
{% endblock %}
<body>
{%  block content %}
    <h1>Все посты</h1>
    {% for post in posts.items %}
        <div class="border-div">
            <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="">
            <h4 class="min-header"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
            <p>{{ post.content }}</p>
        </div>
    {% endfor %}
{% endblock content %}
</body>